name: bootbay
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  sembast: ^2.4.8
  provider: ^5.0.0
  cupertino_icons: ^0.1.3
  flutter_braintree: 0.6.0
  webview_flutter: ^2.0.2
  smooth_star_rating: 1.1.1
  cached_network_image: ^2.4.1
  get_it: ^4.0.1
  image_picker:
  connectivity: ^3.0.6
  intl: ^0.17.0
  currency_text_input_formatter: ^2.1.3
  flutterwave: ^1.0.1
  firebase_auth: ^3.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/signika_bold.ttf
    - assets/fonts/signika_light.ttf
    - assets/fonts/signika_regular.ttf
    - assets/fonts/signika_semi_bold.ttf
    - assets/html/brainTreeDropIn.html
    - assets/images/account_ic.png
    - assets/images/android_new_logo.jpg
    - assets/images/cart_ic.png
    - assets/images/leading_icon.png
    - assets/images/men_landing_ic.png
    - assets/images/search_ic.png
    - assets/images/shop_ic.png
    - assets/images/success.png
    - assets/images/wish_active_ic.png
    - assets/images/wish_inactive_ic.png
    - assets/images/women_landing_ic.png
    - assets/json/env_config_file.json
    - assets/json/json_file.json
    - assets/user.png
    - assets/images/
