/// Generated by AssetsRefGenerator on 2020/06/09
class Res {
  static const String signika_bold = "assets/fonts/signika_bold.ttf";
  static const String signika_light = "assets/fonts/signika_light.ttf";
  static const String signika_regular = "assets/fonts/signika_regular.ttf";
  static const String signika_semi_bold = "assets/fonts/signika_semi_bold.ttf";
  static const String brainTreeDropIn = "assets/html/brainTreeDropIn.html";
  static const String android_new_logo = "assets/images/android_new_logo.jpg";
  static const String success = "assets/images/success.png";
  static const String env_config_file = "assets/json/env_config_file.json";
  static const String json_file = "assets/json/json_file.json";
  static const String user = "assets/user.png";
}
