/// Generated by AssetsRefGenerator on 2020/06/30
class Res {
  static const String signika_bold = "assets/fonts/signika_bold.ttf";
  static const String signika_light = "assets/fonts/signika_light.ttf";
  static const String signika_regular = "assets/fonts/signika_regular.ttf";
  static const String signika_semi_bold = "assets/fonts/signika_semi_bold.ttf";
  static const String brainTreeDropIn = "assets/html/brainTreeDropIn.html";
  static const String yocoDropIn = "assets/html/yocoDropIn.html";
  static const String account_ic = "assets/images/account_ic.png";
  static const String android_new_logo = "assets/images/android_new_logo.jpg";
  static const String cart_ic = "assets/images/cart_ic.png";
  static const String leading_icon = "assets/images/leading_icon.png";
  static const String men_landing_ic = "assets/images/men_landing_ic.png";
  static const String search_ic = "assets/images/search_ic.png";
  static const String shop_ic = "assets/images/shop_ic.png";
  static const String success = "assets/images/success.png";
  static const String wish_active_ic = "assets/images/wish_active_ic.png";
  static const String wish_inactive_ic = "assets/images/wish_inactive_ic.png";
  static const String women_landing_ic = "assets/images/women_landing_ic.png";
  static const String env_config_file = "assets/json/env_config_file.json";
  static const String json_file = "assets/json/json_file.json";
  static const String user = "assets/user.png";
  static const String google_ic = "assets/images/google.png";
  static const String facebook_ic = "assets/images/facebook.png";
  static const String twitter_ic = 'assets/images/twitter.png';
}
